ProcessSalesOrder()
{
	lr_start_transaction("TransactionService_ProcessSalesOrder");

	web_service_call( "StepName=ProcessSalesOrder_101",
		"SOAPMethod=TransactionService|BasicHttpBinding_ISalesTransactionService|ProcessSalesOrder",
		"ResponseParam=response",
		"Service=TransactionService",
		"ExpectedResponse=SoapResult",
		"Snapshot=t1487016404.inf",
		BEGIN_ARGUMENTS,
		"xml:request="
			"<request>"
				"<MachineName>test</MachineName>"
				"<CountryCode>US</CountryCode>"
				"<International nil=\"true\"></International>"
				"<SalesTransactionHeader>"
					"<BankDeposits nil=\"true\"></BankDeposits>"
					"<BusinessDate>2016-09-22T09:38:20.0540625-05:00</BusinessDate>"
					"<CashierNumber>1234567</CashierNumber>"
					"<ChannelType>PointOfSale</ChannelType>"
					"<Currency>USD</Currency>"
					"<Customer>"
						"<Addresses nil=\"true\"></Addresses>"
						"<CustomerActivities nil=\"true\"></CustomerActivities>"
						"<CustomerGuid nil=\"true\"></CustomerGuid>"
						"<CustomerID>1238349631</CustomerID>"
						"<EdgeCardDiscountNumber nil=\"true\"></EdgeCardDiscountNumber>"
						"<EmailAddress nil=\"true\"></EmailAddress>"
						"<FirstName>ab</FirstName>"
						"<HomePhoneNumber nil=\"true\"></HomePhoneNumber>"
						"<Identifications nil=\"true\"></Identifications>"
						"<IssuedUser nil=\"true\"></IssuedUser>"
						"<LastName nil=\"true\"></LastName>"
						"<LoyaltyInfo>"
							"<LoyaltyCardNumber>3876000269233</LoyaltyCardNumber>"
							"<Roles nil=\"true\"></Roles>"
							"<Tier>0</Tier>"
							"<TierExpirationDate>0001-01-01T00:00:00</TierExpirationDate>"
						"</LoyaltyInfo>"
						"<MembershipAttributes nil=\"true\"></MembershipAttributes>"
						"<MembershipIds nil=\"true\"></MembershipIds>"
						"<MembershipProgram nil=\"true\"></MembershipProgram>"
						"<MiddleName nil=\"true\"></MiddleName>"
						"<MobilePhoneNumber nil=\"true\"></MobilePhoneNumber>"
						"<OpenId nil=\"true\"></OpenId>"
						"<Prefix nil=\"true\"></Prefix>"
						"<Suffix nil=\"true\"></Suffix>"
						"<Title nil=\"true\"></Title>"
						"<UserName nil=\"true\"></UserName>"
						"<WorkPhoneNumber nil=\"true\"></WorkPhoneNumber>"
					"</Customer>"
					"<DeviceName nil=\"true\"></DeviceName>"
					"<DiscountCardNumber nil=\"true\"></DiscountCardNumber>"
					"<DiscountCardType>None</DiscountCardType>"
					"<EBCCUsedForPayment>false</EBCCUsedForPayment>"
					"<Employee>"
						"<EmployeeInitials>INIT</EmployeeInitials>"
						"<EmployeeNumber>1234567</EmployeeNumber>"
					"</Employee>"
					"<FSCardUsedForDiscount>false</FSCardUsedForDiscount>"
					"<HardTotals nil=\"true\"></HardTotals>"
					"<HopsGuid nil=\"true\"></HopsGuid>"
					"<InactiveTimeInSeconds>0</InactiveTimeInSeconds>"
					"<IsPawnTransaction>false</IsPawnTransaction>"
					"<LoyaltyID nil=\"true\"></LoyaltyID>"
					"<MachineName>test</MachineName>"
					"<NetCashAmount>15.59</NetCashAmount>"
					"<NetNonCashAmount>0</NetNonCashAmount>"
					"<NonMerchandiseTransaction>false</NonMerchandiseTransaction>"
					"<NonSalesTimeInSeconds>0</NonSalesTimeInSeconds>"
					"<NonTaxableTotal>0</NonTaxableTotal>"
					"<NumberOfDetailRecords>0</NumberOfDetailRecords>"
					"<OrderId nil=\"true\"></OrderId>"
					"<PartnerKey>TEST-US</PartnerKey>"
					"<PostVoidReason nil=\"true\"></PostVoidReason>"
					"<PurchasingEmployee nil=\"true\"></PurchasingEmployee>"
					"<ReceiptEmailAddress>testcustomer@gstop.com</ReceiptEmailAddress>"
					"<RegisterNumber>1</RegisterNumber>"
					"<SalesTransactionHeaderGuid>3d566c7a-2ffa-4008-a575-152a1317aa32</SalesTransactionHeaderGuid>"
					"<SalesTransactionLineItems>"
						"<SalesTransactionLineItem>"
							"<AuditNumber nil=\"true\"></AuditNumber>"
							"<Category>345</Category>"
							"<CommissionAmount>0</CommissionAmount>"
							"<Customer>"
								"<Addresses nil=\"true\"></Addresses>"
								"<CustomerActivities nil=\"true\"></CustomerActivities>"
								"<CustomerGuid nil=\"true\"></CustomerGuid>"
								"<CustomerID>1238349631</CustomerID>"
								"<EdgeCardDiscountNumber nil=\"true\"></EdgeCardDiscountNumber>"
								"<EmailAddress nil=\"true\"></EmailAddress>"
								"<FirstName>ab</FirstName>"
								"<HomePhoneNumber nil=\"true\"></HomePhoneNumber>"
								"<Identifications nil=\"true\"></Identifications>"
								"<IssuedUser nil=\"true\"></IssuedUser>"
								"<LastName nil=\"true\"></LastName>"
								"<LoyaltyInfo nil=\"true\"></LoyaltyInfo>"
								"<MembershipAttributes nil=\"true\"></MembershipAttributes>"
								"<MembershipIds nil=\"true\"></MembershipIds>"
								"<MembershipProgram nil=\"true\"></MembershipProgram>"
								"<MiddleName nil=\"true\"></MiddleName>"
								"<MobilePhoneNumber nil=\"true\"></MobilePhoneNumber>"
								"<OpenId nil=\"true\"></OpenId>"
								"<Prefix nil=\"true\"></Prefix>"
								"<Suffix nil=\"true\"></Suffix>"
								"<Title nil=\"true\"></Title>"
								"<UserName nil=\"true\"></UserName>"
								"<WorkPhoneNumber nil=\"true\"></WorkPhoneNumber>"
							"</Customer>"
							"<Discounts nil=\"true\"></Discounts>"
							"<FrequentCardNumber nil=\"true\"></FrequentCardNumber>"
							"<HopsGuid nil=\"true\"></HopsGuid>"
							"<Return nil=\"true\"></Return>"
							"<ReturnNumber nil=\"true\"></ReturnNumber>"
							"<SKU nil=\"true\"></SKU>"
							"<SNOFDescription nil=\"true\"></SNOFDescription>"
							"<SalesTransactionLineItemGuid>3d566c7a-2ffa-4008-a575-152a1317aa32</SalesTransactionLineItemGuid>"
							"<SerialNumber nil=\"true\"></SerialNumber>"
							"<SubCategory nil=\"true\"></SubCategory>"
						"</SalesTransactionLineItem>"
					"</SalesTransactionLineItems>"
					"<TaxExemptData nil=\"true\"></TaxExemptData>"
					"<Tenders nil=\"true\"></Tenders>"
					"<Total nil=\"true\"></Total>"
				"</SalesTransactionHeader>"
			"</request>",
		END_ARGUMENTS,
		BEGIN_RESULT,
		END_RESULT,
		LAST);

	lr_end_transaction("TransactionService_ProcessSalesOrder", LR_AUTO);

	return 0;
}
